version: '3.8'

services:
  # This is the Database Service
  db:
    image: postgres:15
    container_name: super_app_db
    restart: always
    environment:
      POSTGRES_USER: fahad
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: super_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: